CREATE TABLE IF NOT EXISTS public.staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  whatsapp_number TEXT,
  salary DECIMAL(10, 2),
  status TEXT DEFAULT 'Active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for staff" ON public.staff
FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.salary_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT REFERENCES public.staff(id) ON DELETE CASCADE,
  amount DECIMAL(10, 2) NOT NULL,
  payment_date DATE DEFAULT CURRENT_DATE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.salary_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for salary_payments" ON public.salary_payments
FOR ALL USING (true) WITH CHECK (true);
